
import NavbarMenu from "@/layouts/navbar";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/layouts/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}
      >
        <NavbarMenu/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
